apiVersion: apps/v1
kind: Deployment
metadata:
  name: fraud-consumer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fraud-consumer
  template:
    metadata:
      labels:
        app: fraud-consumer
    spec:
      containers:
      - name: consumer
        image: fraud-consumer:latest
        imagePullPolicy: IfNotPresent
        env:
        - name: KAFKA_BOOTSTRAP_SERVERS
          value: "kafka:9092"
        - name: KAFKA_TOPIC
          value: "fraud-transactions"
